"""Trading signals generated by strategies."""

from dataclasses import dataclass
from decimal import Decimal
from enum import Enum, auto
from typing import Union


class Urgency(Enum):
    """Order urgency level."""
    LOW = auto()       # Post-only limit order
    MEDIUM = auto()    # Standard limit order
    HIGH = auto()      # Aggressive, cross spread if needed
    IMMEDIATE = auto() # Market order


@dataclass(frozen=True)
class Buy:
    """Buy signal."""
    token_id: str
    price: Decimal
    size: Decimal
    urgency: Urgency = Urgency.MEDIUM


@dataclass(frozen=True)
class Sell:
    """Sell signal."""
    token_id: str
    price: Decimal
    size: Decimal
    urgency: Urgency = Urgency.MEDIUM


@dataclass(frozen=True)
class Cancel:
    """Cancel orders for a token."""
    token_id: str


@dataclass(frozen=True)
class Hold:
    """No action."""
    pass


@dataclass(frozen=True)
class Shutdown:
    """Request graceful engine shutdown."""
    reason: str


@dataclass(frozen=True)
class Subscribe:
    """Begin watching a token at runtime.

    The engine initialises a fresh order book, adds the token to its REST
    poller rotation, and reconnects the WebSocket so the new asset id is
    included. Idempotent — a duplicate Subscribe for an already-watched
    token is a no-op.
    """
    token_id: str


@dataclass(frozen=True)
class Unsubscribe:
    """Stop watching a token at runtime.

    The engine cancels any open orders on the token first, releases their
    risk reservations, removes the book from the hub, and reconnects the
    WebSocket. Positions and order history are preserved.
    """
    token_id: str


@dataclass(frozen=True)
class Alert:
    """Propose an order pending human approval.

    The engine queues a `PendingAlert` and fires a notification through
    its configured Notifier (ntfy / Discord). The user approves via
    `pmt engine approve <id>` (or by tapping the notification action
    button), at which point the engine dispatches `suggested` through
    the normal risk + order pipeline. Alerts expire after `ttl_secs`.

    `dedupe_key` keeps a strategy from spamming the same alert each tick
    — if an active alert with this key already exists, the new emission
    is dropped.
    """
    reason: str
    suggested: Union["Buy", "Sell"]
    ttl_secs: int = 600
    dedupe_key: str = ""


# Union type for all signals
Signal = Union[Buy, Sell, Cancel, Hold, Shutdown, Subscribe, Unsubscribe, Alert]
