"""Trading signals generated by strategies."""

from dataclasses import dataclass
from decimal import Decimal
from enum import Enum, auto
from typing import Union


class Urgency(Enum):
    """Order urgency level."""
    LOW = auto()       # Post-only limit order
    MEDIUM = auto()    # Standard limit order
    HIGH = auto()      # Aggressive, cross spread if needed
    IMMEDIATE = auto() # Market order


@dataclass(frozen=True)
class Buy:
    """Buy signal."""
    token_id: str
    price: Decimal
    size: Decimal
    urgency: Urgency = Urgency.MEDIUM


@dataclass(frozen=True)
class Sell:
    """Sell signal."""
    token_id: str
    price: Decimal
    size: Decimal
    urgency: Urgency = Urgency.MEDIUM


@dataclass(frozen=True)
class Cancel:
    """Cancel orders for a token."""
    token_id: str


@dataclass(frozen=True)
class Hold:
    """No action."""
    pass


# Union type for all signals
Signal = Union[Buy, Sell, Cancel, Hold]
