# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polymarket_pb2 as polymarket__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polymarket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClobStub(object):
    """============================================================================
    CLOB Service - Order book and trading operations
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ok = channel.unary_unary(
                '/polymarket.Clob/Ok',
                request_serializer=polymarket__pb2.Empty.SerializeToString,
                response_deserializer=polymarket__pb2.OkResponse.FromString,
                _registered_method=True)
        self.SamplingMarkets = channel.unary_unary(
                '/polymarket.Clob/SamplingMarkets',
                request_serializer=polymarket__pb2.SamplingMarketsRequest.SerializeToString,
                response_deserializer=polymarket__pb2.SamplingMarketsResponse.FromString,
                _registered_method=True)
        self.OrderBook = channel.unary_unary(
                '/polymarket.Clob/OrderBook',
                request_serializer=polymarket__pb2.OrderBookRequest.SerializeToString,
                response_deserializer=polymarket__pb2.OrderBookResponse.FromString,
                _registered_method=True)
        self.Midpoint = channel.unary_unary(
                '/polymarket.Clob/Midpoint',
                request_serializer=polymarket__pb2.MidpointRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PriceResponse.FromString,
                _registered_method=True)
        self.Price = channel.unary_unary(
                '/polymarket.Clob/Price',
                request_serializer=polymarket__pb2.PriceRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PriceResponse.FromString,
                _registered_method=True)
        self.Spread = channel.unary_unary(
                '/polymarket.Clob/Spread',
                request_serializer=polymarket__pb2.SpreadRequest.SerializeToString,
                response_deserializer=polymarket__pb2.SpreadResponse.FromString,
                _registered_method=True)
        self.PostOrder = channel.unary_unary(
                '/polymarket.Clob/PostOrder',
                request_serializer=polymarket__pb2.PostOrderRequest.SerializeToString,
                response_deserializer=polymarket__pb2.PostOrderResponse.FromString,
                _registered_method=True)
        self.OpenOrders = channel.unary_unary(
                '/polymarket.Clob/OpenOrders',
                request_serializer=polymarket__pb2.OpenOrdersRequest.SerializeToString,
                response_deserializer=polymarket__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/polymarket.Clob/CancelOrder',
                request_serializer=polymarket__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=polymarket__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.CancelAllOrders = channel.unary_unary(
                '/polymarket.Clob/CancelAllOrders',
                request_serializer=polymarket__pb2.CancelAllRequest.SerializeToString,
                response_deserializer=polymarket__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Trades = channel.unary_unary(
                '/polymarket.Clob/Trades',
                request_serializer=polymarket__pb2.TradesRequest.SerializeToString,
                response_deserializer=polymarket__pb2.TradesResponse.FromString,
                _registered_method=True)


class ClobServicer(object):
    """============================================================================
    CLOB Service - Order book and trading operations
    ============================================================================

    """

    def Ok(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SamplingMarkets(self, request, context):
        """Get sampling markets with order books
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderBook(self, request, context):
        """Get full order book for a token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Midpoint(self, request, context):
        """Get midpoint price
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Price(self, request, context):
        """Get best price (bid or ask)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Spread(self, request, context):
        """Get spread
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostOrder(self, request, context):
        """Post a signed order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenOrders(self, request, context):
        """Get open orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancel an order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAllOrders(self, request, context):
        """Cancel all orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trades(self, request, context):
        """Get trades
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClobServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ok': grpc.unary_unary_rpc_method_handler(
                    servicer.Ok,
                    request_deserializer=polymarket__pb2.Empty.FromString,
                    response_serializer=polymarket__pb2.OkResponse.SerializeToString,
            ),
            'SamplingMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.SamplingMarkets,
                    request_deserializer=polymarket__pb2.SamplingMarketsRequest.FromString,
                    response_serializer=polymarket__pb2.SamplingMarketsResponse.SerializeToString,
            ),
            'OrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderBook,
                    request_deserializer=polymarket__pb2.OrderBookRequest.FromString,
                    response_serializer=polymarket__pb2.OrderBookResponse.SerializeToString,
            ),
            'Midpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.Midpoint,
                    request_deserializer=polymarket__pb2.MidpointRequest.FromString,
                    response_serializer=polymarket__pb2.PriceResponse.SerializeToString,
            ),
            'Price': grpc.unary_unary_rpc_method_handler(
                    servicer.Price,
                    request_deserializer=polymarket__pb2.PriceRequest.FromString,
                    response_serializer=polymarket__pb2.PriceResponse.SerializeToString,
            ),
            'Spread': grpc.unary_unary_rpc_method_handler(
                    servicer.Spread,
                    request_deserializer=polymarket__pb2.SpreadRequest.FromString,
                    response_serializer=polymarket__pb2.SpreadResponse.SerializeToString,
            ),
            'PostOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PostOrder,
                    request_deserializer=polymarket__pb2.PostOrderRequest.FromString,
                    response_serializer=polymarket__pb2.PostOrderResponse.SerializeToString,
            ),
            'OpenOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenOrders,
                    request_deserializer=polymarket__pb2.OpenOrdersRequest.FromString,
                    response_serializer=polymarket__pb2.OrdersResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=polymarket__pb2.CancelOrderRequest.FromString,
                    response_serializer=polymarket__pb2.CancelResponse.SerializeToString,
            ),
            'CancelAllOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAllOrders,
                    request_deserializer=polymarket__pb2.CancelAllRequest.FromString,
                    response_serializer=polymarket__pb2.CancelResponse.SerializeToString,
            ),
            'Trades': grpc.unary_unary_rpc_method_handler(
                    servicer.Trades,
                    request_deserializer=polymarket__pb2.TradesRequest.FromString,
                    response_serializer=polymarket__pb2.TradesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polymarket.Clob', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polymarket.Clob', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Clob(object):
    """============================================================================
    CLOB Service - Order book and trading operations
    ============================================================================

    """

    @staticmethod
    def Ok(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/Ok',
            polymarket__pb2.Empty.SerializeToString,
            polymarket__pb2.OkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SamplingMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/SamplingMarkets',
            polymarket__pb2.SamplingMarketsRequest.SerializeToString,
            polymarket__pb2.SamplingMarketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/OrderBook',
            polymarket__pb2.OrderBookRequest.SerializeToString,
            polymarket__pb2.OrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Midpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/Midpoint',
            polymarket__pb2.MidpointRequest.SerializeToString,
            polymarket__pb2.PriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/Price',
            polymarket__pb2.PriceRequest.SerializeToString,
            polymarket__pb2.PriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Spread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/Spread',
            polymarket__pb2.SpreadRequest.SerializeToString,
            polymarket__pb2.SpreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/PostOrder',
            polymarket__pb2.PostOrderRequest.SerializeToString,
            polymarket__pb2.PostOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/OpenOrders',
            polymarket__pb2.OpenOrdersRequest.SerializeToString,
            polymarket__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/CancelOrder',
            polymarket__pb2.CancelOrderRequest.SerializeToString,
            polymarket__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAllOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/CancelAllOrders',
            polymarket__pb2.CancelAllRequest.SerializeToString,
            polymarket__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Trades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Clob/Trades',
            polymarket__pb2.TradesRequest.SerializeToString,
            polymarket__pb2.TradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GammaStub(object):
    """============================================================================
    Gamma Service - Market metadata and discovery
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Events = channel.unary_unary(
                '/polymarket.Gamma/Events',
                request_serializer=polymarket__pb2.EventsRequest.SerializeToString,
                response_deserializer=polymarket__pb2.EventsResponse.FromString,
                _registered_method=True)
        self.EventBySlug = channel.unary_unary(
                '/polymarket.Gamma/EventBySlug',
                request_serializer=polymarket__pb2.SlugRequest.SerializeToString,
                response_deserializer=polymarket__pb2.EventResponse.FromString,
                _registered_method=True)
        self.Markets = channel.unary_unary(
                '/polymarket.Gamma/Markets',
                request_serializer=polymarket__pb2.MarketsRequest.SerializeToString,
                response_deserializer=polymarket__pb2.MarketsResponse.FromString,
                _registered_method=True)
        self.MarketBySlug = channel.unary_unary(
                '/polymarket.Gamma/MarketBySlug',
                request_serializer=polymarket__pb2.SlugRequest.SerializeToString,
                response_deserializer=polymarket__pb2.MarketResponse.FromString,
                _registered_method=True)
        self.Tags = channel.unary_unary(
                '/polymarket.Gamma/Tags',
                request_serializer=polymarket__pb2.Empty.SerializeToString,
                response_deserializer=polymarket__pb2.TagsResponse.FromString,
                _registered_method=True)
        self.EventsByTag = channel.unary_unary(
                '/polymarket.Gamma/EventsByTag',
                request_serializer=polymarket__pb2.TagRequest.SerializeToString,
                response_deserializer=polymarket__pb2.EventsResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/polymarket.Gamma/Search',
                request_serializer=polymarket__pb2.SearchRequest.SerializeToString,
                response_deserializer=polymarket__pb2.MarketsResponse.FromString,
                _registered_method=True)
        self.Series = channel.unary_unary(
                '/polymarket.Gamma/Series',
                request_serializer=polymarket__pb2.Empty.SerializeToString,
                response_deserializer=polymarket__pb2.SeriesResponse.FromString,
                _registered_method=True)


class GammaServicer(object):
    """============================================================================
    Gamma Service - Market metadata and discovery
    ============================================================================

    """

    def Events(self, request, context):
        """List events with pagination and filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventBySlug(self, request, context):
        """Get event by slug
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Markets(self, request, context):
        """List markets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarketBySlug(self, request, context):
        """Get market by slug
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tags(self, request, context):
        """Get all tags
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventsByTag(self, request, context):
        """Get events by tag
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search markets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Series(self, request, context):
        """Get recurring series
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GammaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Events': grpc.unary_unary_rpc_method_handler(
                    servicer.Events,
                    request_deserializer=polymarket__pb2.EventsRequest.FromString,
                    response_serializer=polymarket__pb2.EventsResponse.SerializeToString,
            ),
            'EventBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.EventBySlug,
                    request_deserializer=polymarket__pb2.SlugRequest.FromString,
                    response_serializer=polymarket__pb2.EventResponse.SerializeToString,
            ),
            'Markets': grpc.unary_unary_rpc_method_handler(
                    servicer.Markets,
                    request_deserializer=polymarket__pb2.MarketsRequest.FromString,
                    response_serializer=polymarket__pb2.MarketsResponse.SerializeToString,
            ),
            'MarketBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.MarketBySlug,
                    request_deserializer=polymarket__pb2.SlugRequest.FromString,
                    response_serializer=polymarket__pb2.MarketResponse.SerializeToString,
            ),
            'Tags': grpc.unary_unary_rpc_method_handler(
                    servicer.Tags,
                    request_deserializer=polymarket__pb2.Empty.FromString,
                    response_serializer=polymarket__pb2.TagsResponse.SerializeToString,
            ),
            'EventsByTag': grpc.unary_unary_rpc_method_handler(
                    servicer.EventsByTag,
                    request_deserializer=polymarket__pb2.TagRequest.FromString,
                    response_serializer=polymarket__pb2.EventsResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=polymarket__pb2.SearchRequest.FromString,
                    response_serializer=polymarket__pb2.MarketsResponse.SerializeToString,
            ),
            'Series': grpc.unary_unary_rpc_method_handler(
                    servicer.Series,
                    request_deserializer=polymarket__pb2.Empty.FromString,
                    response_serializer=polymarket__pb2.SeriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polymarket.Gamma', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polymarket.Gamma', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gamma(object):
    """============================================================================
    Gamma Service - Market metadata and discovery
    ============================================================================

    """

    @staticmethod
    def Events(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/Events',
            polymarket__pb2.EventsRequest.SerializeToString,
            polymarket__pb2.EventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/EventBySlug',
            polymarket__pb2.SlugRequest.SerializeToString,
            polymarket__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Markets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/Markets',
            polymarket__pb2.MarketsRequest.SerializeToString,
            polymarket__pb2.MarketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarketBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/MarketBySlug',
            polymarket__pb2.SlugRequest.SerializeToString,
            polymarket__pb2.MarketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/Tags',
            polymarket__pb2.Empty.SerializeToString,
            polymarket__pb2.TagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventsByTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/EventsByTag',
            polymarket__pb2.TagRequest.SerializeToString,
            polymarket__pb2.EventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/Search',
            polymarket__pb2.SearchRequest.SerializeToString,
            polymarket__pb2.MarketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Series(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Gamma/Series',
            polymarket__pb2.Empty.SerializeToString,
            polymarket__pb2.SeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChainStub(object):
    """============================================================================
    Chain Service - On-chain balance queries
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UsdcBalance = channel.unary_unary(
                '/polymarket.Chain/UsdcBalance',
                request_serializer=polymarket__pb2.AddressRequest.SerializeToString,
                response_deserializer=polymarket__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.TokenBalance = channel.unary_unary(
                '/polymarket.Chain/TokenBalance',
                request_serializer=polymarket__pb2.TokenBalanceRequest.SerializeToString,
                response_deserializer=polymarket__pb2.BalanceResponse.FromString,
                _registered_method=True)


class ChainServicer(object):
    """============================================================================
    Chain Service - On-chain balance queries
    ============================================================================

    """

    def UsdcBalance(self, request, context):
        """Get USDC balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TokenBalance(self, request, context):
        """Get token balance (CTF outcome tokens)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UsdcBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.UsdcBalance,
                    request_deserializer=polymarket__pb2.AddressRequest.FromString,
                    response_serializer=polymarket__pb2.BalanceResponse.SerializeToString,
            ),
            'TokenBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenBalance,
                    request_deserializer=polymarket__pb2.TokenBalanceRequest.FromString,
                    response_serializer=polymarket__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polymarket.Chain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polymarket.Chain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chain(object):
    """============================================================================
    Chain Service - On-chain balance queries
    ============================================================================

    """

    @staticmethod
    def UsdcBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Chain/UsdcBalance',
            polymarket__pb2.AddressRequest.SerializeToString,
            polymarket__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TokenBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polymarket.Chain/TokenBalance',
            polymarket__pb2.TokenBalanceRequest.SerializeToString,
            polymarket__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
