//! Strategy trait and runtime for trading strategies.

use crate::orderbook::{OrderBook, TradeRecord};
use crate::position::{Fill, PositionTracker};
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use std::collections::HashMap;
use std::sync::Arc;

/// Urgency level for order execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Urgency {
    /// Post-only limit order, willing to wait
    Low,
    /// Standard limit order
    Medium,
    /// Aggressive limit order, cross spread if needed
    High,
    /// Immediate execution, use market order
    Immediate,
}

impl Default for Urgency {
    fn default() -> Self {
        Urgency::Medium
    }
}

/// Trading signal generated by a strategy.
#[derive(Debug, Clone)]
pub enum Signal {
    /// Buy signal
    Buy {
        token_id: String,
        price: Decimal,
        size: Decimal,
        urgency: Urgency,
    },
    /// Sell signal
    Sell {
        token_id: String,
        price: Decimal,
        size: Decimal,
        urgency: Urgency,
    },
    /// Cancel existing orders for a token
    Cancel { token_id: String },
    /// Subscribe to live market data for a token at runtime. The engine
    /// initialises a fresh order book in the MarketDataHub, adds the token
    /// to its REST poller rotation, and re-establishes the WebSocket
    /// subscription so the new book stays current.
    ///
    /// No-op (and harmless) if the token is already subscribed. Strategies
    /// that scan for new markets emit this when they want to start watching
    /// a fresh token.
    Subscribe { token_id: String },
    /// Stop watching a token. The engine cancels any open orders on that
    /// token, removes its book from the MarketDataHub, and re-subscribes
    /// the WebSocket to the remaining tokens. Order history and positions
    /// are preserved.
    Unsubscribe { token_id: String },
    /// Propose an order that requires human approval before execution.
    ///
    /// The engine queues a PendingAlert and pushes a notification through
    /// the configured Notifier (ntfy / Discord). The user calls
    /// `pmt engine approve <id>` (or taps the notification action button)
    /// to execute the suggested signal through the normal risk + order
    /// pipeline, or `pmt engine reject <id>` to drop it. Alerts expire
    /// after `ttl_secs`.
    ///
    /// `dedupe_key` lets a strategy emit the same alert across many ticks
    /// without spamming notifications — if an active alert with the same
    /// key already exists, the new emission is dropped silently.
    Alert {
        reason: String,
        suggested: Box<Signal>,
        ttl_secs: i64,
        dedupe_key: String,
    },
    /// No action
    Hold,
    /// Request graceful shutdown with a reason
    Shutdown { reason: String },
}

/// Market metadata from Gamma API.
///
/// This provides information about the market that a token belongs to,
/// including the question, outcome name, and expiration time.
#[derive(Debug, Clone)]
pub struct MarketInfo {
    /// The market question (e.g., "Will X happen?")
    pub question: String,
    /// Which outcome this token represents (e.g., "Yes" or "No")
    pub outcome: String,
    /// URL slug for the market
    pub slug: String,
    /// When the market expires/resolves
    pub end_date: Option<DateTime<Utc>>,
    /// Hours until expiry (computed at context creation time)
    pub hours_until_expiry: Option<f64>,
    /// Total liquidity in USDC (from Gamma API)
    pub liquidity: Option<f64>,
}

impl MarketInfo {
    /// Create a new MarketInfo.
    pub fn new(
        question: String,
        outcome: String,
        slug: String,
        end_date: Option<DateTime<Utc>>,
    ) -> Self {
        Self::with_liquidity(question, outcome, slug, end_date, None)
    }

    /// Create a new MarketInfo with liquidity data.
    pub fn with_liquidity(
        question: String,
        outcome: String,
        slug: String,
        end_date: Option<DateTime<Utc>>,
        liquidity: Option<f64>,
    ) -> Self {
        let hours_until_expiry = end_date.map(|end| {
            let now = Utc::now();
            let duration = end.signed_duration_since(now);
            duration.num_seconds() as f64 / 3600.0
        });

        Self {
            question,
            outcome,
            slug,
            end_date,
            hours_until_expiry,
            liquidity,
        }
    }
}

/// Context provided to strategies for decision making.
#[derive(Debug, Clone)]
pub struct StrategyContext {
    /// Current timestamp
    pub timestamp: DateTime<Utc>,
    /// Order books by token ID (full depth)
    pub order_books: HashMap<String, Arc<OrderBook>>,
    /// Rolling public-trade history per token, bounded by the hub's
    /// `max_trade_age` (1h by default). Strategies use this to compute
    /// volume / price-change signals over windows the live book can't
    /// reveal. Empty if the trade tape hasn't seen anything for a token
    /// yet, or if it failed to resolve the condition_id.
    pub trade_history: HashMap<String, Vec<TradeRecord>>,
    /// Current positions
    pub positions: PositionTracker,
    /// Market metadata by token ID (from Gamma API)
    pub markets: HashMap<String, MarketInfo>,
    /// Total unrealized P&L
    pub unrealized_pnl: Decimal,
    /// Total realized P&L
    pub realized_pnl: Decimal,
    /// Available USDC balance for trading
    pub usdc_balance: Decimal,
}

impl StrategyContext {
    /// Trades for a token within the last `window_secs` seconds.
    /// Convenience over filtering `trade_history` manually.
    pub fn recent_trades(&self, token_id: &str, window_secs: i64) -> Vec<&TradeRecord> {
        let cutoff = self.timestamp.timestamp() - window_secs;
        self.trade_history
            .get(token_id)
            .map(|v| v.iter().filter(|t| t.timestamp >= cutoff).collect())
            .unwrap_or_default()
    }

    /// Sum of size across trades for a token in the last `window_secs`
    /// seconds. Useful for volume-spike detection.
    pub fn volume_in_window(&self, token_id: &str, window_secs: i64) -> Decimal {
        self.recent_trades(token_id, window_secs)
            .iter()
            .map(|t| t.size)
            .sum()
    }

    /// Owned snapshot of currently-subscribed token ids the strategy can
    /// reason about. Strategies driven by a market scanner (rather than a
    /// hardcoded list) iterate this instead of a module-level constant.
    pub fn subscribed_tokens(&self) -> Vec<String> {
        self.order_books.keys().cloned().collect()
    }
}


/// Trait for implementing trading strategies.
pub trait Strategy: Send + Sync {
    /// Unique identifier for this strategy.
    fn id(&self) -> &str;

    /// Token IDs this strategy wants to subscribe to.
    fn subscriptions(&self) -> Vec<String>;

    /// Minimum interval between `on_tick` calls for this strategy, in
    /// milliseconds. The engine's global tick may fire more frequently;
    /// `StrategyRuntime` skips calls that arrive sooner than this interval.
    ///
    /// Default is 1000ms — strategies declaring a larger interval (e.g.
    /// market makers that re-quote every 10s) just override this and the
    /// runtime won't waste API calls in between.
    fn tick_interval_ms(&self) -> u64 {
        1000
    }

    /// Called on each tick with current market state.
    /// Returns signals for order management.
    fn on_tick(&mut self, ctx: &StrategyContext) -> Vec<Signal>;

    /// Optional gamma-based market filter that the engine's scanner uses
    /// to keep this strategy's subscription set current. Returning
    /// `Some(filter)` tells the engine: every PMENGINE_SCAN_INTERVAL_S,
    /// fetch markets matching `filter` from gamma and reconcile against
    /// the currently-subscribed token set — Subscribe newcomers,
    /// Unsubscribe drop-outs. `None` (the default) keeps the
    /// statically-declared `subscriptions()` set.
    fn market_filter(&self) -> Option<crate::gamma::MarketFilter> {
        None
    }

    /// Called when an order is filled.
    fn on_fill(&mut self, _fill: &Fill) {}

    /// Called on shutdown for cleanup.
    fn on_shutdown(&mut self) {}
}

/// Owned summary of a registered strategy.
#[derive(Debug, Clone)]
pub struct StrategySummary {
    pub id: String,
    pub tick_interval_ms: u64,
    pub subscriptions: Vec<String>,
    pub last_tick_at: Option<std::time::Instant>,
}

/// Runtime for executing multiple strategies.
pub struct StrategyRuntime {
    strategies: Vec<Box<dyn Strategy>>,
    /// Last `on_tick` invocation time per strategy index. Used to gate calls
    /// by each strategy's declared `tick_interval_ms`.
    last_tick_at: Vec<Option<std::time::Instant>>,
}

impl StrategyRuntime {
    pub fn new() -> Self {
        Self {
            strategies: Vec::new(),
            last_tick_at: Vec::new(),
        }
    }

    /// Register a strategy.
    pub fn register(&mut self, strategy: Box<dyn Strategy>) {
        tracing::info!(
            strategy_id = strategy.id(),
            tick_interval_ms = strategy.tick_interval_ms(),
            "Registering strategy"
        );
        self.strategies.push(strategy);
        self.last_tick_at.push(None);
    }

    /// Owned snapshot of every registered strategy's `market_filter()`,
    /// for the engine's scanner task to consume. Strategies returning
    /// `None` (the default) are skipped — scanner only acts on opt-ins.
    pub fn market_filters(&self) -> Vec<crate::gamma::MarketFilter> {
        self.strategies
            .iter()
            .filter_map(|s| s.market_filter())
            .collect()
    }

    /// Owned summary of a registered strategy, for introspection by the
    /// control plane. The `last_tick_at` Instant is monotonic; callers that
    /// need a wall-clock time should compute it from `Utc::now()` minus
    /// `Instant::now().duration_since(t)` at the same observation point.
    pub fn summaries(&self) -> Vec<StrategySummary> {
        self.strategies
            .iter()
            .enumerate()
            .map(|(i, s)| StrategySummary {
                id: s.id().to_string(),
                tick_interval_ms: s.tick_interval_ms(),
                subscriptions: s.subscriptions(),
                last_tick_at: self.last_tick_at[i],
            })
            .collect()
    }

    /// Get all token subscriptions from all strategies.
    pub fn all_subscriptions(&self) -> Vec<String> {
        let mut subs: Vec<String> = self
            .strategies
            .iter()
            .flat_map(|s| s.subscriptions())
            .collect();
        subs.sort();
        subs.dedup();
        subs
    }

    /// Run all strategies that are due for a tick and collect signals.
    ///
    /// Each strategy is only invoked if at least its declared
    /// `tick_interval_ms` has elapsed since its last call. The engine's
    /// global tick may fire faster — strategies declaring slower cadences
    /// (e.g. market makers re-quoting every 10s) won't churn API calls.
    pub fn tick(&mut self, ctx: &StrategyContext) -> Vec<Signal> {
        let mut all_signals = Vec::new();
        let now = std::time::Instant::now();
        for (i, strategy) in self.strategies.iter_mut().enumerate() {
            let interval = std::time::Duration::from_millis(strategy.tick_interval_ms());
            let due = match self.last_tick_at[i] {
                None => true,
                Some(t) => now.duration_since(t) >= interval,
            };
            if !due {
                continue;
            }
            self.last_tick_at[i] = Some(now);
            let signals = strategy.on_tick(ctx);
            for signal in signals {
                tracing::debug!(strategy_id = strategy.id(), ?signal, "Strategy signal");
                all_signals.push(signal);
            }
        }
        all_signals
    }

    /// Notify all strategies of a fill.
    pub fn on_fill(&mut self, fill: &Fill) {
        for strategy in &mut self.strategies {
            strategy.on_fill(fill);
        }
    }

    /// Shutdown all strategies.
    pub fn shutdown(&mut self) {
        for strategy in &mut self.strategies {
            tracing::info!(strategy_id = strategy.id(), "Shutting down strategy");
            strategy.on_shutdown();
        }
    }
}

impl Default for StrategyRuntime {
    fn default() -> Self {
        Self::new()
    }
}

/// Example: Simple market maker strategy (for testing).
pub struct DummyStrategy {
    id: String,
    tokens: Vec<String>,
}

impl DummyStrategy {
    pub fn new(id: &str, tokens: Vec<String>) -> Self {
        Self {
            id: id.to_string(),
            tokens,
        }
    }
}

impl Strategy for DummyStrategy {
    fn id(&self) -> &str {
        &self.id
    }

    fn subscriptions(&self) -> Vec<String> {
        self.tokens.clone()
    }

    fn on_tick(&mut self, ctx: &StrategyContext) -> Vec<Signal> {
        // Just log market state, don't trade
        for token_id in &self.tokens {
            if let Some(book) = ctx.order_books.get(token_id) {
                tracing::debug!(
                    token_id,
                    best_bid = ?book.best_bid().map(|l| l.price),
                    best_ask = ?book.best_ask().map(|l| l.price),
                    mid = ?book.mid_price(),
                    bid_levels = book.bids.len(),
                    ask_levels = book.asks.len(),
                    "Market state"
                );
            }
        }
        vec![Signal::Hold]
    }
}
