"""Pure tests for the crypto up/down semantics parser and fee math."""

import json

import pytest

from polymarket import crypto as crypto_mod
from polymarket.crypto import parse_semantics, slug_of, taker_fee


def _event(desc: str) -> dict:
    return {
        "slug": "test-event",
        "title": "Bitcoin Up or Down",
        "markets": [{
            "question": "Bitcoin Up or Down - test",
            "description": desc,
            "outcomes": json.dumps(["Up", "Down"]),
            "clobTokenIds": json.dumps(["111", "222"]),
            "eventStartTime": "2026-08-22T20:30:00Z",
            "endDate": "2026-08-22T20:45:00Z",
            "feeSchedule": {"rate": 0.07, "takerOnly": True},
        }],
    }


def test_slug_of():
    assert slug_of("https://polymarket.com/event/btc-updown-15m-1787430600") == "btc-updown-15m-1787430600"
    assert slug_of("btc-updown-15m-1787430600?tid=x") == "btc-updown-15m-1787430600"


def test_parse_semantics_twap():
    sem = parse_semantics(_event(
        'This market will resolve to "Up" if the time-weighted average price (TWAP) '
        "of Bitcoin, generated by Chainlink ... BTC/USD TWAP data stream"))
    assert sem["kind"] == "twap"
    assert sem["symbol"] == "BTCUSDT"
    assert sem["token_up"] == "111" and sem["token_down"] == "222"
    assert sem["fee_rate"] == 0.07
    assert sem["end"] - sem["start"] == 900


def test_parse_semantics_close_open():
    sem = parse_semantics(_event(
        'resolve to "Up" if the close price is greater than or equal to the open '
        "price for the BTC/USDT 1 hour candle"))
    assert sem["kind"] == "close_open"
    assert sem["symbol"] == "BTCUSDT"


def test_parse_semantics_rejects_unknown():
    with pytest.raises(ValueError):
        parse_semantics(_event("resolves YES if the president says bitcoin"))


def test_taker_fee_cheaper_side():
    assert taker_fee(0.91, 0.07) == pytest.approx(0.07 * 0.09)
    assert taker_fee(0.09, 0.07) == pytest.approx(0.07 * 0.09)
    assert taker_fee(0.5, 0.0) == 0.0


# ---------- one source for the shared constants ----------

def test_taker_fee_is_the_shared_constants_implementation():
    from polymarket import constants

    assert crypto_mod.taker_fee is constants.taker_fee
    assert crypto_mod.BASIS_NOISE_BP is constants.BASIS_NOISE_BP


def test_shadow_prices_fees_at_the_shared_rate():
    from polymarket import constants, shadow

    assert shadow.FEE_RATE is constants.FEE_RATE
    assert shadow.fee(0.91) == pytest.approx(constants.taker_fee(0.91))


def test_taker_fee_defaults_to_the_live_rate():
    from polymarket.constants import FEE_RATE, taker_fee

    assert taker_fee(0.91) == pytest.approx(FEE_RATE * 0.09)
