"""The predictor port is EXACT or it is wrong.

`pilot2/vectors/terminal_p_up.json` was generated by running the vault's own
`strategy2/calfit/predict.py` — the module that produced calibrated_model.md's
numbers — and every expected value is stored as `float.hex()`. These tests
assert bit-for-bit equality, not approximate agreement: a port that is close
is a DIFFERENT model, and the report's Brier/log-loss deltas do not transfer
to it.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

from pilot2 import predict

VECTORS = json.loads(
    (Path(predict.__file__).parent / "vectors" / "terminal_p_up.json").read_text())


def _f(x):
    return float("nan") if x == "nan" else float.fromhex(x)


def _same(got: float, want: float) -> bool:
    """Bit-exact, with nan == nan (the spec returns nan for a bad input and
    that IS the contract — a port that returns 0.5 there prices a coin flip
    on a window it cannot see)."""
    if math.isnan(want):
        return math.isnan(got)
    return got == want


@pytest.mark.parametrize("case", VECTORS["terminal_p_up"], ids=lambda c: c["name"])
def test_terminal_p_up_matches_the_frozen_vault_vectors(case):
    got = predict.terminal_p_up(case["ref"], case["spot"], _f(case["sigma_s"]),
                                list(case["banked"]), case["now"], case["end"])
    want = _f(case["p_up"])
    assert _same(got, want), f"{case['name']}: {got!r} != {want!r}"


@pytest.mark.parametrize("case", VECTORS["sigma_per_second"], ids=lambda c: c["name"])
def test_sigma_per_second_matches_the_frozen_vectors(case):
    got = predict.sigma_per_second(list(case["ts"]), list(case["px"]))
    assert _same(got, _f(case["sigma"]))


@pytest.mark.parametrize("case", VECTORS["devig"], ids=lambda c: c["name"])
def test_devig_matches_the_frozen_vectors(case):
    got = predict.devig(case["up_px"], case["dn_px"])
    assert _same(got, _f(case["p"]))


@pytest.mark.parametrize("case", VECTORS["blended_p_up"], ids=lambda c: c["name"])
def test_blended_p_up_matches_the_frozen_vectors(case):
    got = predict.blended_p_up(_f(case["model_p"]), case["book_up"], case["book_dn"], case["w"])
    assert _same(got, _f(case["p"]))


def test_banked_mass_is_seconds_elapsed_not_prints_received():
    """The 281-of-400 lesson, pinned on the vector built to discriminate it.

    Three prints spanning 40 elapsed seconds. Banking the ELAPSED span prices
    the window DOWN (p=0.303); banking the three prints received would price
    it UP. A port that counts prints fails here and nowhere else.
    """
    case = next(c for c in VECTORS["terminal_p_up"]
                if c["name"] == "gappy_banked_discriminates_rule")
    got = predict.terminal_p_up(case["ref"], case["spot"], _f(case["sigma_s"]),
                                list(case["banked"]), case["now"], case["end"])
    assert got < 0.5, "the elapsed-seconds rule prices this window DOWN"

    b = case["banked"]
    n = len(b)
    print_counted_mean = (sum(b) / n * n + (60 - n) * case["spot"]) / 60.0
    assert print_counted_mean > case["ref"], (
        "the vector must actually discriminate: counting prints prices it UP")

    dense = next(c for c in VECTORS["terminal_p_up"] if c["name"] == "dense_banked_same_span")
    assert predict.terminal_p_up(dense["ref"], dense["spot"], _f(dense["sigma_s"]),
                                 list(dense["banked"]), dense["now"], dense["end"]) == got, \
        "a gappy window and a dense one over the same span must price identically"


def test_settlement_width_is_sixty_seconds_at_every_duration():
    """`settle_tw_secs()` returning 30.0 below 300s is the live bug the whole
    calibrated model is downstream of. There is one width."""
    assert predict.SETTLE_WIDTH_S == 60.0
    # A 5m window: the banked span opens at end-60, not end-30.
    end = 1787400300.0
    full = [100.0] * 60
    assert predict.terminal_p_up(99.0, 100.0, 1e-4, full, end, end) == 1.0
    # 30 seconds of banked mass at end-30 leaves 30s of walk, not zero.
    p = predict.terminal_p_up(100.0, 100.0, 1e-4, [100.0] * 30, end - 30.0, end)
    assert 0.0 < p < 1.0, "half the settlement window is still unwritten at end-30"


def test_devig_refuses_to_invent_a_market_opinion():
    """A one-sided book has no implied probability. Substituting
    `1 - other_side` manufactures an opinion the market never expressed."""
    assert math.isnan(predict.devig(0.62, float("nan")))
    assert math.isnan(predict.devig(float("nan"), 0.40))
    assert math.isnan(predict.devig(0.0, 0.0))


def test_blend_falls_back_to_whichever_estimator_exists():
    assert predict.blended_p_up(0.8, float("nan"), 0.4, 0.55) == 0.8
    assert predict.blended_p_up(float("nan"), 0.6, 0.4, 0.55) == predict.devig(0.6, 0.4)


def test_max_stale_is_the_spec_contract():
    assert predict.MAX_STALE_S == 5.0
