"""PREDICTOR SPEC — a verbatim port of `strategy2/calfit/predict.py`.

This file is a TRANSCRIPTION, not a re-derivation. The vault's predictor spec
is the artefact that produced `calibrated_model.md`'s numbers (23% Brier / 54%
log-loss over the incumbent, and the only policy in that study whose paper P&L
interval excludes zero). `vectors/terminal_p_up.json` was generated by running
the VAULT module, and `tests/test_pilot2_predict.py` asserts this file
reproduces it bit-for-bit. If the two ever diverge, this file is wrong.

Do not "improve" the arithmetic. Three rules were each measured, and each has
a frozen vector standing on it:

  1. **Width is 60s at EVERY duration**, 5m included. `settle_tw_secs()`
     returning 30.0 below 300s is the live bug the whole model is downstream of
     (60s right on 72.9% of the windows where the two widths disagree).
  2. **The reference is the TWAP print AT window start**, not the minute mark
     before it.
  3. **Banked mass is SECONDS ELAPSED, not prints received.** A second the
     relay dropped still happened and still lands in the settlement average.
     Counting prints makes a gappy window look less decided than it is — the
     vault's self-test caught this at 281 of 400 rows, and
     `gappy_banked_discriminates_rule` is the vector that fails if a port
     gets it wrong (the two rules price opposite sides of that one).
"""

from __future__ import annotations

import math

SETTLE_WIDTH_S = 60.0
MAX_STALE_S = 5.0


def terminal_p_up(ref: float, spot: float, sigma_s: float,
                  banked: list[float], now: float, end: float) -> float:
    """P(terminal 60s-TWAP >= ref) under a driftless walk from `spot`.

    Settlement is T = mean(spot over [end-60, end]). Split it in two: the
    seconds already printed (`banked`) are known, and the rest is a random
    walk from `spot`. The mean of an averaging window that opens `d` seconds
    from now and runs `n` seconds has variance sigma^2 * (d + n/3) — the d
    term is the drift-out before averaging starts, the n/3 is the averaging
    itself. That single expression is the whole model.
    """
    if not (ref > 0.0 and spot > 0.0) or sigma_s <= 0.0 or not math.isfinite(sigma_s):
        return float("nan")
    # The banked mass is measured in SECONDS ELAPSED, not in prints received.
    # A second the relay dropped still happened and still contributes to the
    # settlement average, so the elapsed span is banked at the observed mean
    # rather than being silently shortened. Counting prints instead makes a
    # gappy window look less decided than it is.
    n_banked = 0
    banked_sum = 0.0
    if banked:
        elapsed_lock = int(min(now, end) - (end - SETTLE_WIDTH_S))
        n_banked = int(min(SETTLE_WIDTH_S, max(len(banked), elapsed_lock)))
        banked_sum = (math.fsum(banked) / len(banked)) * n_banked
    n_rem = SETTLE_WIDTH_S - n_banked
    if n_rem <= 0.0:
        return 1.0 if (banked_sum / SETTLE_WIDTH_S) >= ref else 0.0
    d = max(0.0, (end - SETTLE_WIDTH_S) - now)
    mean = (banked_sum + n_rem * spot) / SETTLE_WIDTH_S
    sd = spot * (n_rem / SETTLE_WIDTH_S) * sigma_s * math.sqrt(d + n_rem / 3.0)
    if sd <= 1e-12:
        return 1.0 if mean >= ref else 0.0
    return 0.5 * math.erfc(-((mean - ref) / sd) / math.sqrt(2.0))


def devig(up_px: float, dn_px: float) -> float:
    """Book-implied P(up). nan when a side is unquoted — never substitute
    1 - other_side; a one-sided book has no implied probability."""
    if not (math.isfinite(up_px) and math.isfinite(dn_px)):
        return float("nan")
    tot = up_px + dn_px
    return up_px / tot if tot > 1e-9 else float("nan")


def blended_p_up(model_p: float, book_up: float, book_dn: float, w: float) -> float:
    """The SHIPPING estimator: w on the model, 1-w on the market.

    `w` is not a constant — it must be re-fit on recent history by minimising
    Brier, and it moved 0.00 -> 0.20 -> 0.40 -> 0.55 across this corpus's four
    walk-forward folds as evidence accumulated. Freezing it at today's value
    would be fitting a moving target. With no book, the model stands alone.
    """
    b = devig(book_up, book_dn)
    if not math.isfinite(b):
        return model_p
    if not math.isfinite(model_p):
        return b
    return w * model_p + (1.0 - w) * b


def sigma_per_second(ts: list[float], px: list[float]) -> float:
    """Trailing per-second log-return stdev over CONSECUTIVE seconds only.

    Skipping non-consecutive pairs is not fussiness: the recorder drops
    scattered seconds, and treating a 34s hole as one 1s tick reads as a
    single enormous return and inflates sigma enough to flatten the model.
    """
    rs = [math.log(px[i + 1] / px[i])
          for i in range(len(px) - 1)
          if abs(ts[i + 1] - ts[i] - 1.0) < 1e-6 and px[i] > 0.0 and px[i + 1] > 0.0]
    if len(rs) < 4:
        return float("nan")
    mu = math.fsum(rs) / len(rs)
    return math.sqrt(math.fsum((r - mu) ** 2 for r in rs) / (len(rs) - 1))
