//! Auto-generated strategy registry - DO NOT EDIT MANUALLY
//! Regenerate with: pmstrat transpile --all
//!
//! Every .rs file in this directory gets a `mod` line here. A file with a
//! `pub struct X` that carries `impl Strategy for X` is a strategy: declared
//! `mod x;`, re-exported, and registered below. Anything else is a helper
//! module, declared `pub(crate) mod x;` so the rest of the crate can reach it.
//! A strategy file that needs crate-wide visibility of its own module says so
//! in the file with a `// pmstrat: pub(crate)` marker line — nothing here is
//! hand-maintained.
//!
//! Files under `private/` (the pm-trade/pmt-strategies submodule mount) keep
//! their `crate::strategies::<name>` module paths via `#[path]` declarations;
//! their every item here is gated on `cfg(private_strategies)`, set by
//! build.rs when the submodule is initialized. This one committed file
//! compiles identically in public clones (no submodule) and private
//! checkouts — regenerate it with the submodule inited.

mod example;
#[cfg(private_strategies)]
#[path = "private/updown.rs"]
pub(crate) mod updown;
#[cfg(private_strategies)]
#[path = "private/updown2.rs"]
mod updown2;
#[cfg(private_strategies)]
#[path = "private/updown2_model.rs"]
pub(crate) mod updown2_model;
#[cfg(private_strategies)]
#[path = "private/updown_model.rs"]
pub(crate) mod updown_model;
#[cfg(private_strategies)]
#[path = "private/updown_oracle.rs"]
pub(crate) mod updown_oracle;
#[cfg(private_strategies)]
#[path = "private/updown_rtds.rs"]
pub(crate) mod updown_rtds;
#[cfg(private_strategies)]
#[path = "private/updown_state.rs"]
pub(crate) mod updown_state;

use std::collections::HashMap;
use crate::strategy::Strategy;

pub use example::Example;
#[cfg(private_strategies)]
pub use updown::Updown;
#[cfg(private_strategies)]
pub use updown2::Updown2;

/// Information about a strategy in the registry.
pub struct StrategyInfo {
    /// Factory function to create a new instance of the strategy.
    pub factory: fn() -> Box<dyn Strategy>,
}

/// Returns the strategy registry - a map of strategy names to their info.
///
/// This function is called by the engine to look up strategies by name.
/// The registry is auto-generated by `pmstrat transpile --all`.
pub fn registry() -> HashMap<&'static str, StrategyInfo> {
    let mut m = HashMap::new();

    m.insert("example", StrategyInfo {
        factory: || Box::new(example::Example::new()),
    });

    #[cfg(private_strategies)]
    m.insert("updown", StrategyInfo {
        factory: || Box::new(updown::Updown::new()),
    });

    #[cfg(private_strategies)]
    m.insert("updown2", StrategyInfo {
        factory: || Box::new(updown2::Updown2::new()),
    });

    m
}
